<?php

namespace App\Domain\Entities;

/**
 * UserManagementEntities - domain Layer - entities
 * 
 * This is a sample file generated by Laravel Architex for the domain layer.
 * Replace this with your actual implementation.
 */
class UserManagementEntities
{
    /**
     * Constructor
     */
    public function __construct()
    {
        // TODO: Add your constructor logic
    }

    /**
     * Sample method for entities
     */
    public function sampleMethod(): mixed
    {
        // TODO: Implement your entities logic
        
        return null;
    }
} 