<?php

namespace App\Domain\Events;

/**
 * UserManagementEvents - domain Layer - events
 * 
 * This is a sample file generated by Laravel Architex for the domain layer.
 * Replace this with your actual implementation.
 */
class UserManagementEvents
{
    /**
     * Constructor
     */
    public function __construct()
    {
        // TODO: Add your constructor logic
    }

    /**
     * Sample method for events
     */
    public function sampleMethod(): mixed
    {
        // TODO: Implement your events logic
        
        return null;
    }
} 