<?php

namespace App\UI\Controllers;

/**
 * UserManagementControllers - ui Layer - controllers
 * 
 * This is a sample file generated by Laravel Architex for the ui layer.
 * Replace this with your actual implementation.
 */
class UserManagementControllers
{
    /**
     * Constructor
     */
    public function __construct()
    {
        // TODO: Add your constructor logic
    }

    /**
     * Sample method for controllers
     */
    public function sampleMethod(): mixed
    {
        // TODO: Implement your controllers logic
        
        return null;
    }
} 