<?php

namespace App\UI\Middleware;

/**
 * UserManagementMiddleware - ui Layer - middleware
 * 
 * This is a sample file generated by Laravel Architex for the ui layer.
 * Replace this with your actual implementation.
 */
class UserManagementMiddleware
{
    /**
     * Constructor
     */
    public function __construct()
    {
        // TODO: Add your constructor logic
    }

    /**
     * Sample method for middleware
     */
    public function sampleMethod(): mixed
    {
        // TODO: Implement your middleware logic
        
        return null;
    }
} 